# Runs Renovate dependency updater hourly on a self-hosted runner.
#
# Only the RENOVATE_AUTODISCOVER_FILTER value changes per repo.
#
# Template source: shakenfist/development/templates/renovate/

name: Renovate dependency updater

permissions:
  contents: read

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  renovate:
    runs-on: [self-hosted, static]
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v46.1.0
        with:
          token: ${{ secrets.RENOVATE_TOKEN }}
        env:
          RENOVATE_AUTODISCOVER: "true"
          RENOVATE_AUTODISCOVER_FILTER: "shakenfist/{{GITHUB_REPO_NAME}}"
